// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmttdugozceovfjpxufh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtdHRkdWdvemNlb3ZmanB4dWZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NzY3MDgsImV4cCI6MjA3MjA1MjcwOH0.-eLFRH3o7xzH28kAWHCkLBocX1Wx9LGM9VLh8UMH8qg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});